export const categories = [
  { id: 1, content: 'Electronics' },
  { id: 2, content: 'Clothing' },
  { id: 3, content: 'Home & Kitchen' },
  { id: 4, content: 'Sports & Outdoors' },
  { id: 5, content: 'Beauty & Personal Care' },
  { id: 6, content: 'Toys & Games' },
  { id: 7, content: 'Books' },
  { id: 8, content: 'Jewelry' },
  { id: 9, content: 'Health & Wellness' },
  { id: 10, content: 'Automotive' },
  { id: 11, content: 'Grocery' },
  { id: 12, content: 'Furniture' },
  { id: 13, content: 'Shoes' },
  { id: 14, content: 'Pet Supplies' },
  { id: 15, content: 'Office Supplies' },
  { id: 16, content: 'Baby Products' },
  { id: 17, content: 'Garden & Outdoor' },
  { id: 18, content: 'Movies & Music' },
  { id: 19, content: 'Watches' },
  { id: 20, content: 'Fitness' },
  { id: 21, content: 'Home Improvement' },
  { id: 22, content: 'Food & Drink' },
  { id: 23, content: 'Computers & Accessories' },
  { id: 24, content: 'Travel' },
  { id: 25, content: 'Art & Crafts' },
];

export const brands = [
  { id: 1, content: 'Sony' },
  { id: 2, content: 'Nike' },
  { id: 3, content: 'Samsung' },
  { id: 4, content: 'Adidas' },
  { id: 5, content: 'Apple' },
  { id: 6, content: 'Puma' },
  { id: 7, content: 'AmazonBasics' },
  { id: 8, content: 'Rolex' },
  { id: 9, content: 'Nestle' },
  { id: 10, content: 'Toyota' },
  { id: 11, content: 'Coca-Cola' },
  { id: 12, content: 'IKEA' },
  { id: 13, content: 'Reebok' },
  { id: 14, content: 'Pedigree' },
  { id: 15, content: 'HP' },
  { id: 16, content: 'Gerber' },
  { id: 17, content: "Lowe's" },
  { id: 18, content: 'Disney' },
  { id: 19, content: 'Timex' },
  { id: 20, content: 'Fitbit' },
  { id: 21, content: 'Home Depot' },
  { id: 22, content: 'Kraft' },
  { id: 23, content: 'Dell' },
  { id: 24, content: 'Delta Airlines' },
  { id: 25, content: 'Crayola' },
];
