export const categories = [
  { id: 1, name: 'Electronics' },
  { id: 2, name: 'Clothing' },
  { id: 3, name: 'Home & Kitchen' },
  { id: 4, name: 'Sports & Outdoors' },
  { id: 5, name: 'Beauty & Personal Care' },
  { id: 6, name: 'Toys & Games' },
  { id: 7, name: 'Books' },
  { id: 8, name: 'Jewelry' },
  { id: 9, name: 'Health & Wellness' },
  { id: 10, name: 'Automotive' },
  { id: 11, name: 'Grocery' },
  { id: 12, name: 'Furniture' },
  { id: 13, name: 'Shoes' },
  { id: 14, name: 'Pet Supplies' },
  { id: 15, name: 'Office Supplies' },
  { id: 16, name: 'Baby Products' },
  { id: 17, name: 'Garden & Outdoor' },
  { id: 18, name: 'Movies & Music' },
  { id: 19, name: 'Watches' },
  { id: 20, name: 'Fitness' },
  { id: 21, name: 'Home Improvement' },
  { id: 22, name: 'Food & Drink' },
  { id: 23, name: 'Computers & Accessories' },
  { id: 24, name: 'Travel' },
  { id: 25, name: 'Art & Crafts' },
];

export const brands = [
  { id: 1, name: 'Sony' },
  { id: 2, name: 'Nike' },
  { id: 3, name: 'Samsung' },
  { id: 4, name: 'Adidas' },
  { id: 5, name: 'Apple' },
  { id: 6, name: 'Puma' },
  { id: 7, name: 'AmazonBasics' },
  { id: 8, name: 'Rolex' },
  { id: 9, name: 'Nestle' },
  { id: 10, name: 'Toyota' },
  { id: 11, name: 'Coca-Cola' },
  { id: 12, name: 'IKEA' },
  { id: 13, name: 'Reebok' },
  { id: 14, name: 'Pedigree' },
  { id: 15, name: 'HP' },
  { id: 16, name: 'Gerber' },
  { id: 17, name: "Lowe's" },
  { id: 18, name: 'Disney' },
  { id: 19, name: 'Timex' },
  { id: 20, name: 'Fitbit' },
  { id: 21, name: 'Home Depot' },
  { id: 22, name: 'Kraft' },
  { id: 23, name: 'Dell' },
  { id: 24, name: 'Delta Airlines' },
  { id: 25, name: 'Crayola' },
];
